# Simple Makefile for out-of-tree module build

obj-m := anemometer.o
anemometer-objs := anemometer-main.o anemometer-chrdev.o anemometer-sysfs.o anemometer-dt.o anemometer-configfs.o

KDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

.PHONY: all clean
