# Standalone Makefile for out-of-tree build

obj-m := anemometer.o
anemometer-y := anemometer-main.o \
		anemometer-chrdev.o \
		anemometer-sysfs.o \
		anemometer-dt.o \
		anemometer-configfs.o

KDIR ?= /lib/modules/$(shell uname -r)/build

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

.PHONY: all clean
